Use fantasticon to generate web fonts
twbs/icons pull request #515
Opened 2020-12-07 19:06 UTC by mdo

Replaces #287 with a new dependency, fantasticon.

2020-12-08 10:07 UTC, XhmikosR commented on docs/assets/scss/docs.scss
> +// stylelint-disable
Better be more explicit here?

2020-12-08 10:07 UTC, XhmikosR commented on .fantasticonrc.js
> +};
EOF newline

2020-12-08 10:09 UTC, XhmikosR commented on src/html.hbs
> +</html>
EOF newline

2020-12-08 10:09 UTC, XhmikosR commented on package.json
> +    "fonts"
Better be more explicit here like this:

```suggestion
    "fonts/*.{eot,ttf,woff,woff2}"
```

2020-12-08 10:10 UTC, XhmikosR requested changes
Also,

* the hbs files seem unused
* package.json is missing the new devDependency
* the script should be added to another script (or we run it separately) so that's tested on CI

2020-12-08 17:19 UTC, mdo commented on package.json
> +    "fonts"
I want the whole fonts directory for now. Too weird?

2020-12-08 17:50 UTC, mdo commented on docs/assets/scss/docs.scss
> +// stylelint-disable
Done, but it's a mouthful haha.

2020-12-08 17:52 UTC, mdo commented
> * the hbs files seem unused

`.hbs` files are indeed used—they help generate the CSS and HTML in the `font` directory. They're specified in `.fantasticonrc.js`.

2020-12-08 17:57 UTC, mdo commented
> * package.json is missing the new devDependency
> * the script should be added to another script (or we run it separately) so that's tested on CI

Done and done.

- Hooked into the `icons` script
- Added devDependency
- Renamed the `font` script to `icons-font` for consistency
- Added the `font` dir to the zip script

2020-12-08 19:05 UTC, XhmikosR commented on package.json
> +    "fonts"
Yup. Because unneeded files might be included in the npm package, even files not tracked by git.

2020-12-08 19:06 UTC, XhmikosR commented
Just a question: do you really want to add eot and ttf fonts? woff and woff2 should be more than enough. Heck, you could even just generate woff2 if you don't care about IE :P

* https://caniuse.com/?search=woff
* https://caniuse.com/?search=woff2

2020-12-08 19:08 UTC, XhmikosR commented on package.json
> +    "fonts"
Actually, now that I see the folder contents, ignore my comment. It's just too many filetypes to specify.

2020-12-08 19:10 UTC, XhmikosR commented on src/html.hbs
> +  <meta charset="UTF-8">
Maybe lowercase this?

2020-12-08 19:10 UTC, XhmikosR commented on src/html.hbs
> +      grid-template-columns: repeat(auto-fit, minmax(100px, 1fr) );
Shouldn't this be prefixed?

2020-12-08 19:20 UTC, mdo commented on src/html.hbs
> +      grid-template-columns: repeat(auto-fit, minmax(100px, 1fr) );
I don't think so? https://deploy-preview-31813--twbs-bootstrap.netlify.app/docs/5.0/layout/css-grid/ doesn't show any prefixing...

2020-12-08 19:22 UTC, XhmikosR commented on src/html.hbs
> +      grid-template-columns: repeat(auto-fit, minmax(100px, 1fr) );
Yeah, it needs to be manually made since that's not handled by any tools: it's hardcoded.

2020-12-08 19:28 UTC, XhmikosR commented on src/html.hbs
> +      grid-template-columns: repeat(auto-fit, minmax(100px, 1fr) );
NVM, sorry, I just re-read what you wrote. Indeed, it's fine as is :)

2020-12-09 03:56 UTC, mdo commented
Dropping EOT and TTF for now since we can always add back later, but removing is always more difficult.

Good to go after this I think!

2020-12-09 16:07 UTC, XhmikosR commented on docs/assets/scss/docs.scss
> +// stylelint-disable
Indeed, better revert this one, sorry!

2020-12-09 16:09 UTC, XhmikosR commented
Minus my last comment, I think this looks good :)

2020-12-09 16:10 UTC, XhmikosR commented
I wonder though, is fonts/index.html supposed to be served? It's not using relative paths to the CSS AFAICT.

2020-12-09 19:13 UTC, mdo commented
> I wonder though, is fonts/index.html supposed to be served? It's not using relative paths to the CSS AFAICT.

Yeah, I want that served. It's used locally for previewing, and eventually I'll have it up to date and part of the full nav.

2020-12-09 19:18 UTC, XhmikosR commented
Actually, I just saw you hooked the font directory as font so it's already available indeed: https://deploy-preview-515--bootstrap-icons.netlify.app/font/ and included in sitemap.

2020-12-09 19:20 UTC, XhmikosR approved these changes

2020-12-09 19:27 UTC, merged

2020-12-12 10:22 UTC, TechQuery commented
@mdo @XhmikosR There is no **CSS & Web Font** files in the [ZIP bundle][1] & [NPM package][2]...

[1]: https://github.com/twbs/icons/releases/download/v1.2.0/bootstrap-icons-1.2.0.zip
[2]: https://www.jsdelivr.com/package/npm/bootstrap-icons

2020-12-12 12:25 UTC, XhmikosR commented
The zip file does have the font for me. For the npm package see #538 .