Include Bootstrap via npm
twbs/icons pull request #547
Opened 2020-12-13 23:30 UTC by mdo

Adds the JS to make the navbar work on mobile. Also drops the manually included CSS file and it's associated docs-purge task. Might revisit how to restore PurgeCSS later, and perhaps do a custom JS bundle if we think it'd help.

Fixes #543.

2020-12-15 06:58 UTC, XhmikosR commented on package.json
> -  "dependencies": {},
Let's keep this here so that it's clear there are no deps

2020-12-15 06:59 UTC, XhmikosR commented on font/index.html
> +  <link rel="stylesheet" href="/assets/css/docs.css">
I don't think we should bundle the CSS with the docs CSS.

2020-12-15 12:58 UTC, XhmikosR requested changes

2020-12-15 12:58 UTC, XhmikosR commented on package.json
> -    "docs-purge": "npm run docs-build && purgecss --css docs/static/assets/css/bootstrap.min.css --content \"_site/**/*.html\" --output docs/static/assets/css/",
Should remove the purgecss devDependency if it's no longer used

2020-12-16 03:25 UTC, mdo commented on font/index.html
> +  <link rel="stylesheet" href="/assets/css/docs.css">
Leaving for now ahead of a custom build.

2020-12-17 09:54 UTC, XhmikosR commented
This doesn't work as it is. Which is one of the reasons I haven't landed such change upstream; there's no error if the source file isn't found.

I suggest that we drop this patch as is and we do it properly once and for all.

2020-12-23 00:08 UTC, mdo commented
Closing for #583.

2020-12-23 00:08 UTC, closed without merging